### ISSUE TITLE
Collection of transformed chunk data

### ISSUE THREAD

**Issue by GitiHubi** [sarthak268/DisCont#2]
Dear Sarthak, 

Many thanks for the excellent paper and publishing your code on GitHub. Much appreciated!

I have a question regarding the collection of the transformed chunks in line 164 of the training loop contained in the train.py module. Shouldn't it read: 

`transformed_chunks[i * FLAGS.z_num_chunks : (i+1) * FLAGS.z_num_chunks] = curr_cv_full_view`

instead of:

`transformed_chunks[i*FLAGS.z_num_chunks : (i+1)*FLAGS.z_num_chunks]`

to collect the distinct transformed chunks and to subsequently compute the center loss? I fear that otherwise, the information contained in the `transformed_chunks` tensor won't contain any updated data other than the initialisation. 

Thanks again,
Marco

**Comment by sarthak268** [comment]
Thank you for pointing out. We will make the required changes to code.

**Comment by vishaal27** [comment]
There was an error on our side in uploading the camera ready version of the code. Thanks for pointing it, it has been fixed now.

**Comment by GitiHubi** [comment]
Many thanks for the swift fix. That's fantastic.
