### ISSUE TITLE
Question about the way to update context vector

### ISSUE THREAD

**Issue by MilkKnight** [sarthak268/DisCont#3]
Hello Sarthak268,

Thanks for sharing your code. The idea is great.

I checked the code and I have a question,

You create variable cv_full_view:
https://github.com/sarthak268/DisCont/blob/a1b6d75887bac24bf73495e724062e01bcdd22cd/train.py#L110
But somehow you overwrite it:
https://github.com/sarthak268/DisCont/blob/a1b6d75887bac24bf73495e724062e01bcdd22cd/train.py#L149

If I'm not wrong, I think the idea is to use the **_stored_** cv_full_view (centers) to get the center_loss, update it, then keep doing this procedure, right? Otherwise, there is no point to do:
https://github.com/sarthak268/DisCont/blob/a1b6d75887bac24bf73495e724062e01bcdd22cd/train.py#L185
cause you get new cv_full_view every iteration.

Thanks again! Great paper!

**Comment by vishaal27** [comment]
Hey, thank you for pointing out this issue. This was something that we had overlooked previously. We have now updated the code to reflect the consistent updates to the context vector in every iteration, and have re-trained and validated all the models specified in the paper. The qualitative and quantitative results are very similar to the original paper (infact we observe gains in the informativeness scores for 2 datasets).
